---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-rc
  labels:
    app: play
spec:
  replicas: 2
  selector:
    matchLabels:
      app: play
  template:
    metadata:
      labels:
        app: play
    spec:
      containers:
        - name: myimage
          image: 9492453554/myimage111:latest
          ports:
          - containerPort: 8080
