---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcss-rs
  namespace: production
  labels:
    app: pcc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pcc
  template:
    metadata:
      labels:
        app: pcc
    spec:
      containers:
        - name: myimage
          image: 9492453554/myimage0:latest
          ports:
          - containerPort: 8080
